Repository Hi-lingual/Hilingual-iOS, pull requests merged in 2025-09, with the labels that each got.

#255 [feat] 게시된 일기 뷰 차단하기 모달 및 Mock Service 연결
  Hilingual/App/AppDIContainer.swift
  HilingualPresentation/Sources/Presentation/SharedDiary/SharedDiaryViewController.swift
  HilingualPresentation/Sources/Presentation/SharedDiary/SharedDiaryViewModel.swift
Labels: 🔨 feat, 🐯 소은

#256 [chore] SharedDiary / DiaryDetail GUI 수정 사항 반영
  HilingualPresentation/Sources/Presentation/Common/Components/HighlightTextView.swift
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Icon/28/ic_save_default_28_ios.imageset/ic_save_default_28_ios.svg
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Icon/28/ic_save_variant_28_ios.imageset/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Icon/28/ic_save_variant_28_ios.imageset/ic_save_28_ios.svg
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Icon/28/ic_save_variant_28_ios.imageset/ic_save_variant_28_ios.svg
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Icon/36/ic_save_default_36_ios.imageset/ic_save_default_36_ios.svg
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Icon/36/ic_save_variant_36_ios.imageset/ic_save_variant_36_ios.svg
  HilingualPresentation/Sources/Presentation/DiaryDetail/DiaryDetailViewController.swift
  HilingualPresentation/Sources/Presentation/DiaryDetail/FeedbackView.swift
  HilingualPresentation/Sources/Presentation/DiaryDetail/VocaView.swift
  HilingualPresentation/Sources/Presentation/SharedDiary/SharedDiaryViewController.swift
Labels: ✏️ chore, 🐯 소은

#263 [fix] CalendarView auto layout 제약 충돌 해결
  HilingualPresentation/Sources/Presentation/Common/Components/Calendar/CalendarContentView.swift
  HilingualPresentation/Sources/Presentation/Common/Components/Calendar/CalendarHeaderView.swift
  HilingualPresentation/Sources/Presentation/Common/Components/Calendar/CalendarView.swift
Labels: ⚒️ fix, 🦊 영서

#265 [network] 소셜로그인 API 연결
  HilingualData/Sources/HilingualData/Mapper/LoginResponseDTO+Mapper.swift
  HilingualNetwork/Sources/HilingualNetwork/API/AuthAPI.swift
  HilingualNetwork/Sources/HilingualNetwork/API/OnBoardingAPI.swift
  HilingualNetwork/Sources/HilingualNetwork/DTO/LoginResponseDTO.swift
  HilingualNetwork/Sources/HilingualNetwork/Service/DefaultAuthService.swift
  HilingualNetwork/Sources/HilingualNetwork/Service/DefaultOnBoardingService.swift
  HilingualPresentation/Sources/Presentation/Splash/SplashViewModel.swift
Labels: 🛜 network, 🐥 현주

#270 [network] 회원가입 api 연결 +
  Hilingual/App/AppDIContainer.swift
  HilingualData/Sources/HilingualData/Repository/DefaultOnBoardingRepository.swift
  HilingualData/Sources/HilingualData/Repository/DefaultPresignedImageUploadRepository.swift
  HilingualDomain/Sources/HilingualDomain/Entity/ProfileEntity.swift
  HilingualDomain/Sources/HilingualDomain/Interface/Repository/PresignedImageUploadRepository.swift
  HilingualDomain/Sources/HilingualDomain/UseCase/OnBoardingUseCase.swift
  HilingualDomain/Sources/HilingualDomain/UseCase/UploadImageUseCase.swift
  HilingualNetwork/Sources/HilingualNetwork/API/OnBoardingAPI.swift
  HilingualNetwork/Sources/HilingualNetwork/API/PresignedURLAPI.swift
  HilingualNetwork/Sources/HilingualNetwork/DTO/OnBoardingReponseDTO.swift
  HilingualNetwork/Sources/HilingualNetwork/DTO/PresignedURLDTO.swift
  HilingualNetwork/Sources/HilingualNetwork/Service/DefaultOnBoardingService.swift
  HilingualNetwork/Sources/HilingualNetwork/Service/PresignedURLService.swift
  HilingualPresentation/Sources/Presentation/Common/Components/AgreementModalView/AgreementModalView.swift
  HilingualPresentation/Sources/Presentation/Common/Components/Modal.swift
  HilingualPresentation/Sources/Presentation/OnBoarding/OnBoardingView.swift
  HilingualPresentation/Sources/Presentation/OnBoarding/OnBoardingViewController.swift
  HilingualPresentation/Sources/Presentation/OnBoarding/OnBoardingViewModel.swift
  HilingualPresentation/Sources/Presentation/Splash/SplashViewModel.swift
Labels: 🛜 network, 🐥 현주

#276 [network] SharedDiary 관련 API 연결
  Hilingual/App/AppDIContainer.swift
  HilingualData/Sources/HilingualData/Repository/DefaultDeleteDiaryRepository.swift
  HilingualData/Sources/HilingualData/Repository/DefaultPublishDiaryRepository.swift
  HilingualData/Sources/HilingualData/Repository/DefaultSharedDiaryRepository.swift
  HilingualDomain/Sources/HilingualDomain/Interface/Repository/PublishDiaryRepository.swift
  HilingualDomain/Sources/HilingualDomain/UseCase/DefaultPublishDiaryUseCase.swift
  HilingualNetwork/Sources/HilingualNetwork/API/DiaryControlAPI.swift
  HilingualNetwork/Sources/HilingualNetwork/API/SharedDiaryAPI.swift
  HilingualNetwork/Sources/HilingualNetwork/DTO/SharedDiaryResponseDTO.swift
  HilingualNetwork/Sources/HilingualNetwork/Service/DefaultDiaryControlService.swift
  HilingualNetwork/Sources/HilingualNetwork/Service/DefaultSharedDiaryService.swift
  HilingualNetwork/Sources/HilingualNetwork/Service/Mock/MockDeleteDiaryService.swift
  HilingualNetwork/Sources/HilingualNetwork/Service/Mock/MockPublishDiaryService.swift
  HilingualNetwork/Sources/HilingualNetwork/Service/Mock/MockSharedDiaryService.swift
  HilingualPresentation/Sources/Presentation/Common/Components/HighlightTextView.swift
  HilingualPresentation/Sources/Presentation/Common/Components/WordCard.swift
  HilingualPresentation/Sources/Presentation/DiaryDetail/DiaryDetailViewController.swift
  HilingualPresentation/Sources/Presentation/DiaryDetail/DiaryDetailViewModel.swift
  HilingualPresentation/Sources/Presentation/DiaryDetail/VocaView.swift
  HilingualPresentation/Sources/Presentation/DiaryDetail/VocaViewController.swift
  HilingualPresentation/Sources/Presentation/DiaryDetail/VocaViewModel.swift
  HilingualPresentation/Sources/Presentation/SharedDiary/SharedDiaryViewController.swift
  HilingualPresentation/Sources/Presentation/SharedDiary/SharedDiaryViewModel.swift
Labels: 🛜 network, 🐯 소은

#284 [chore] 재사용셀 내 이미지 빈 배열 처리
  HilingualPresentation/Sources/Presentation/FollowList/FollowListViewModel.swift
  HilingualPresentation/Sources/Presentation/FollowList/TableView/FollowListCell.swift
Labels: ✏️ chore, 🐰 혜연

#274 [network] Home API 연결
  Hilingual/App/AppDIContainer.swift
  HilingualData/Sources/HilingualData/Repository/DefaultHomeRepository.swift
  HilingualDomain/Sources/HilingualDomain/Interface/Repository/HomeRepository.swift
  HilingualDomain/Sources/HilingualDomain/UseCase/HomeUseCase.swift
  HilingualNetwork/Sources/HilingualNetwork/API/HomeAPI.swift
  HilingualNetwork/Sources/HilingualNetwork/Service/DefaultHomeService.swift
  HilingualNetwork/Sources/HilingualNetwork/Service/MockHomeService.swift
  HilingualPresentation/Sources/Presentation/Common/Components/Calendar/CalendarView.swift
  HilingualPresentation/Sources/Presentation/Common/Components/HomeView/ProfileView.swift
  HilingualPresentation/Sources/Presentation/Common/Components/HomeView/SelectedInfo.swift
  HilingualPresentation/Sources/Presentation/Common/Components/TextView.swift
  HilingualPresentation/Sources/Presentation/Home/HomeViewController.swift
  HilingualPresentation/Sources/Presentation/Home/HomeViewModel.swift
Labels: 🛜 network, 🐰 혜연

#306 [refactor] QA 2차 이슈 수정
  HilingualPresentation/Sources/Presentation/Common/Base/TabBarViewController.swift
  HilingualPresentation/Sources/Presentation/Common/Components/SegmentedControl.swift
  HilingualPresentation/Sources/Presentation/Feed/FeedView.swift
  HilingualPresentation/Sources/Presentation/Feed/FeedViewController.swift
  HilingualPresentation/Sources/Presentation/FeedList/FeedList.swift
  HilingualPresentation/Sources/Presentation/FeedList/FeedListViewController.swift
  HilingualPresentation/Sources/Presentation/FeedProfile/FeedProfileViewController.swift
  HilingualPresentation/Sources/Presentation/FeedProfile/MyFeed/MyFeedProfileView.swift
  HilingualPresentation/Sources/Presentation/FeedProfile/MyFeed/MyFeedProfileViewController.swift
  HilingualPresentation/Sources/Presentation/FeedProfile/UserFeed/UserFeedProfileView.swift
  HilingualPresentation/Sources/Presentation/FeedProfile/UserFeed/UserFeedViewController.swift
Labels: ⭐️ refactor, 🦊 영서

#329 [refactor] 차단 후 피드 자동 재검색 구현
  HilingualPresentation/Sources/Presentation/FeedSearch/FeedSearchViewController.swift
Labels: ⭐️ refactor, 🐰 혜연
