Repository Hi-lingual/Hilingual-iOS, pull requests merged in 2025-08, with the labels that each got.

#174 [chore] 데모데이 로직 복구
  HilingualPresentation/Sources/Presentation/Common/Components/HomeView/SelectedInfo.swift
Labels: ✏️ chore, 🦊 영서

#185 [refactor] 캘린더 슬라이드 기능 구현
  HilingualPresentation/Sources/Presentation/Common/Components/Calendar/CalendarContentView.swift
  HilingualPresentation/Sources/Presentation/Common/Components/Calendar/CalendarHeaderView.swift
  HilingualPresentation/Sources/Presentation/Common/Components/Calendar/CalendarView.swift
  HilingualPresentation/Sources/Presentation/Common/Components/Calendar/CustomCalendarCell.swift
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Icon/16/ic_arrow_down_16_ios.imageset/ic_arrow_down_16_ios.svg
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Icon/20/ic_arrow_left_20_ios.imageset/ic_arrow_left_20_ios.svg
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Icon/20/ic_arrow_right_20_ios.imageset/ic_arrow_right_20_ios.svg
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Icon/24/ic_arrow_down_24_ios.imageset/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Icon/24/ic_arrow_down_24_ios.imageset/ic_arrow_down_24_ios.svg
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Icon/24/ic_arrow_left_g_24_ios.imageset/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Icon/24/ic_arrow_left_g_24_ios.imageset/ic_arrow_left_g_24_ios.svg
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Icon/24/ic_arrow_right_g_24_ios.imageset/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Icon/24/ic_arrow_right_g_24_ios.imageset/ic_arrow_right_24_g_ios.svg
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Image/img_bubble_unfilled_ios.imageset/img_bubble_unfilled_ios.svg
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Image/img_bubble_written_ios.imageset/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Image/img_bubble_written_ios.imageset/img_bubble_selected.svg
  HilingualPresentation/Sources/Presentation/Home/HomeView.swift
Labels: ⭐️ refactor, 🦊 영서

#186 [refactor] diaryDetail 코드 가독성 측면 리팩토링
  Hilingual/App/AppDIContainer.swift
  HilingualData/Sources/HilingualData/Repository/DefaultRecommendedVocaRespository.swift
  HilingualDomain/Sources/HilingualDomain/Entity/RecommendedExpressionEntity.swift
  HilingualDomain/Sources/HilingualDomain/Interface/Repository/RecommendedExpressionRepository.swift
  HilingualDomain/Sources/HilingualDomain/Interface/Repository/RecommendedVocaRepository.swift
  HilingualDomain/Sources/HilingualDomain/UseCase/RecommendedExpressionUseCase.swift
  HilingualDomain/Sources/HilingualDomain/UseCase/RecommendedUseCase.swift
  HilingualNetwork/Sources/HilingualNetwork/API/DiaryDetailAPI.swift
  HilingualNetwork/Sources/HilingualNetwork/API/FeedbackAPI.swift
  HilingualNetwork/Sources/HilingualNetwork/API/RecommendedVocaAPI.swift
  HilingualNetwork/Sources/HilingualNetwork/DTO/RecommendedExpressionResponseDTO.swift
  HilingualNetwork/Sources/HilingualNetwork/Service/DefaultRecommendedExpressionService.swift
  HilingualNetwork/Sources/HilingualNetwork/Service/DefaultRecommendedVocaService.swift
  HilingualNetwork/Sources/HilingualNetwork/Service/FeedbackService.swift
  HilingualPresentation/Sources/Presentation/Common/Factory/ViewControllerFactory.swift
  HilingualPresentation/Sources/Presentation/DiaryDetail/DetailImageView.swift
  HilingualPresentation/Sources/Presentation/DiaryDetail/DiaryDetailView.swift
  HilingualPresentation/Sources/Presentation/DiaryDetail/DiaryDetailViewController.swift
  HilingualPresentation/Sources/Presentation/DiaryDetail/DiaryDetailViewModel.swift
  HilingualPresentation/Sources/Presentation/DiaryDetail/Dummy/CorrectionData.swift
  HilingualPresentation/Sources/Presentation/DiaryDetail/Dummy/FeedbackData.swift
  HilingualPresentation/Sources/Presentation/DiaryDetail/Dummy/PhraseData.swift
  HilingualPresentation/Sources/Presentation/DiaryDetail/FeedbackView.swift
  HilingualPresentation/Sources/Presentation/DiaryDetail/FeedbackViewController.swift
  HilingualPresentation/Sources/Presentation/DiaryDetail/FeedbackViewModel.swift
  HilingualPresentation/Sources/Presentation/DiaryDetail/VocaView.swift
  HilingualPresentation/Sources/Presentation/DiaryDetail/VocaViewController.swift
  HilingualPresentation/Sources/Presentation/DiaryDetail/VocaViewModel.swift
Labels: ⭐️ refactor, 🐯 소은

#188 [refactor] diaryDetail 기능 관련 리팩토링
  Hilingual/App/AppDIContainer.swift
  HilingualDomain/Sources/HilingualDomain/UseCase/MockUseCase/MockDiaryDetailUseCase.swift
  HilingualDomain/Sources/HilingualDomain/UseCase/MockUseCase/MockFeedbackUseCase.swift
  HilingualDomain/Sources/HilingualDomain/UseCase/MockUseCase/MockRecommendedUseCase.swift
  HilingualPresentation/Sources/Presentation/Common/Components/WordCard.swift
  HilingualPresentation/Sources/Presentation/DiaryDetail/DiaryDetailViewController.swift
  HilingualPresentation/Sources/Presentation/DiaryDetail/FeedbackView.swift
  HilingualPresentation/Sources/Presentation/DiaryDetail/FeedbackViewController.swift
  HilingualPresentation/Sources/Presentation/DiaryDetail/VocaView.swift
Labels: ⭐️ refactor, 🐯 소은

#201 [chore] DiaryDetail 내의 ImageDetail 풀프레임 이슈 대응
  HilingualDomain/Sources/HilingualDomain/UseCase/MockUseCase/MockDiaryDetailUseCase.swift
  HilingualPresentation/Sources/Presentation/DiaryDetail/DetailImageView.swift
Labels: ✏️ chore, 🐯 소은

#205 [chore] Font Height 설정 추가
  HilingualPresentation/Sources/Presentation/Common/Components/CTAButton.swift
  HilingualPresentation/Sources/Presentation/Common/Components/CustomToggle.swift
  HilingualPresentation/Sources/Presentation/Common/Components/Dialog.swift
  HilingualPresentation/Sources/Presentation/Common/Components/Dropdown.swift
  HilingualPresentation/Sources/Presentation/Common/Components/HighlightTextView.swift
  HilingualPresentation/Sources/Presentation/Common/Components/HighlightingFeedback.swift
  HilingualPresentation/Sources/Presentation/Common/Components/HomeView/CardPreview.swift
  HilingualPresentation/Sources/Presentation/Common/Components/HomeView/CardTopicView.swift
  HilingualPresentation/Sources/Presentation/Common/Components/TextField.swift
  HilingualPresentation/Sources/Presentation/Common/Components/TextView.swift
  HilingualPresentation/Sources/Presentation/Common/Components/WordCard.swift
  HilingualPresentation/Sources/Presentation/Common/Extensions/NSAttributedString+.swift
  HilingualPresentation/Sources/Presentation/DiaryDetail/FeedbackView.swift
  HilingualPresentation/Sources/Presentation/DiaryDetail/VocaView.swift
  HilingualPresentation/Sources/Presentation/DiaryWriting/DiaryWritingView.swift
  HilingualPresentation/Sources/Presentation/OnBoarding/OnBoardingView.swift
  HilingualPresentation/Sources/Presentation/WordBook/TableView/WordBookHeaderView.swift
  HilingualPresentation/Sources/Presentation/WordBook/WordBookEmptyView.swift
  HilingualPresentation/Sources/Presentation/WordBook/WordBookView.swift
Labels: ✏️ chore, 🐯 소은

#206 [feat] FollowButton 컴포넌트 구현
  HilingualPresentation/Sources/Presentation/Common/Components/FollowButton.swift
Labels: 🔨 feat, 🐰 혜연

#216 [feat] 피드 엠티뷰 컴포넌트 구현
  HilingualPresentation/Sources/Presentation/Common/Components/NoFeedView.swift
Labels: 🔨 feat, 🦊 영서

#213 [feat] 액션메뉴 컴포넌트 구현
  Hilingual.xcodeproj/project.pbxproj
  HilingualPresentation/Sources/Presentation/Common/Components/ActionMenu.swift
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Icon/24/ic_delete_24_ios.imageset/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Icon/24/ic_delete_24_ios.imageset/ic_delete_24_ios.svg
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Icon/24/ic_hide_24_ios.imageset/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Icon/24/ic_hide_24_ios.imageset/ic_hide_24_ios.svg
Labels: 🔨 feat, 🦊 영서

#222 [feat] 인증코드 구현 + 온보딩 인증 로직 추가
  Hilingual/App/AppDIContainer.swift
  HilingualData/Sources/HilingualData/Repository/DefaultVerificationCodeRepository.swift
  HilingualDomain/Sources/HilingualDomain/Interface/Repository/VerificationCodeRepository.swift
  HilingualDomain/Sources/HilingualDomain/UseCase/VerificationCodeUseCase.swift
  HilingualNetwork/Sources/HilingualNetwork/Service/VerificationCodeService.swift
  HilingualPresentation/Sources/Presentation/Common/Components/AgreementModalView/AgreementModalView.swift
  HilingualPresentation/Sources/Presentation/Common/Components/AgreementModalView/AgreementRow.swift
  HilingualPresentation/Sources/Presentation/Common/Components/VerificationCodeInputView.swift
  HilingualPresentation/Sources/Presentation/Common/Factory/ViewControllerFactory.swift
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Icon/28/ic_check_black_28_ios.imageset/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Icon/28/ic_check_black_28_ios.imageset/ic_check_circle_28_ios.svg
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Icon/28/ic_check_gray_28_ios.imageset/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Icon/28/ic_check_gray_28_ios.imageset/ic_check_circle_28_iosd.svg
  HilingualPresentation/Sources/Presentation/OnBoarding/OnBoardingView.swift
  HilingualPresentation/Sources/Presentation/OnBoarding/OnBoardingViewController.swift
  HilingualPresentation/Sources/Presentation/OnBoarding/OnBoardingViewModel.swift
  HilingualPresentation/Sources/Presentation/VerificationCode/VerificationCodeView.swift
  HilingualPresentation/Sources/Presentation/VerificationCode/VerificationCodeViewController.swift
  HilingualPresentation/Sources/Presentation/VerificationCode/VerificationCodeViewModel.swift
Labels: 🔨 feat, 🐥 현주

#225 [feat] 피드 내 검색기능 구현
  Hilingual/App/AppDIContainer.swift
  HilingualPresentation/Sources/Presentation/Common/Components/FollowButton.swift
  HilingualPresentation/Sources/Presentation/Common/Components/Protocol/UserDisplayable.swift
  HilingualPresentation/Sources/Presentation/Common/Components/SearchBar.swift
  HilingualPresentation/Sources/Presentation/Common/Extensions/BaseUIViewController+Navigation.swift
  HilingualPresentation/Sources/Presentation/Common/Factory/ViewControllerFactory.swift
  HilingualPresentation/Sources/Presentation/FeedSearch/FeedSearchEmptyView.swift
  HilingualPresentation/Sources/Presentation/FeedSearch/FeedSearchView.swift
  HilingualPresentation/Sources/Presentation/FeedSearch/FeedSearchViewController.swift
  HilingualPresentation/Sources/Presentation/FeedSearch/FeedSearchViewModel.swift
  HilingualPresentation/Sources/Presentation/FollowList/FollowListViewModel.swift
  HilingualPresentation/Sources/Presentation/FollowList/TableView/FollowListCell.swift
Labels: 🔨 feat, 🐰 혜연

#235 [feat] 피드 홈 & 피드 프로필 구현
  Hilingual/App/AppDIContainer.swift
  HilingualData/Sources/HilingualData/Repository/DefaultFeedProfileInfoRepository.swift
  HilingualData/Sources/HilingualData/Repository/DefaultFeedProfileRepository.swift
  HilingualData/Sources/HilingualData/Repository/DefaultFeedRepository.swift
  HilingualDomain/Sources/HilingualDomain/Entity/FeedEntity.swift
  HilingualDomain/Sources/HilingualDomain/Entity/FeedProfileInfoEntity.swift
  HilingualDomain/Sources/HilingualDomain/Interface/Repository/FeedProfileInfoRepository.swift
  HilingualDomain/Sources/HilingualDomain/Interface/Repository/FeedProfileRepository.swift
  HilingualDomain/Sources/HilingualDomain/Interface/Repository/FeedRepository.swift
  HilingualDomain/Sources/HilingualDomain/UseCase/FeedProfileInfoUseCase.swift
  HilingualDomain/Sources/HilingualDomain/UseCase/FeedProfileUseCase.swift
  HilingualDomain/Sources/HilingualDomain/UseCase/FeedUseCase.swift
  HilingualNetwork/Sources/HilingualNetwork/API/FeedAPI.swift
  HilingualNetwork/Sources/HilingualNetwork/API/FeedProfileAPI.swift
  HilingualNetwork/Sources/HilingualNetwork/DTO/FeedDTO.swift
  HilingualNetwork/Sources/HilingualNetwork/DTO/FeedProfileDTO.swift
  HilingualNetwork/Sources/HilingualNetwork/DTO/FeedProfileInfoDTO.swift
  HilingualNetwork/Sources/HilingualNetwork/Service/DefaultFeedProfileInfoService.swift
  HilingualNetwork/Sources/HilingualNetwork/Service/DefaultFeedProfileService.swift
  HilingualNetwork/Sources/HilingualNetwork/Service/DefaultFeedService.swift
  HilingualNetwork/Sources/HilingualNetwork/Service/Mock/MockFeedProfileInfoService.swift
  HilingualNetwork/Sources/HilingualNetwork/Service/Mock/MockFeedProfileService.swift
  HilingualNetwork/Sources/HilingualNetwork/Service/Mock/MockFeedService.swift
  HilingualPresentation/Sources/Presentation/Common/Base/TabBarViewController.swift
  HilingualPresentation/Sources/Presentation/Common/Components/BlockModal.swift
  HilingualPresentation/Sources/Presentation/Common/Components/Feed/FeedDiaryCell.swift
  HilingualPresentation/Sources/Presentation/Common/Components/Feed/FeedProfileView.swift
  HilingualPresentation/Sources/Presentation/Common/Extensions/BaseUIViewController+Navigation.swift
  HilingualPresentation/Sources/Presentation/Common/Factory/ViewControllerFactory.swift
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Icon/20/ic_check_20_ios.imageset/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Icon/20/ic_check_20_ios.imageset/ic_check_20_ios.svg
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Icon/24/ic_block_24_2_ios.imageset/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Icon/24/ic_block_24_2_ios.imageset/ic_block_24_2_ios.svg
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Icon/24/ic_search_24_ios.imageset/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Icon/24/ic_search_24_ios.imageset/ic_search_24_ios.svg
  HilingualPresentation/Sources/Presentation/Feed/FeedView.swift
  HilingualPresentation/Sources/Presentation/Feed/FeedViewController.swift
  HilingualPresentation/Sources/Presentation/Feed/FeedViewModel.swift
  HilingualPresentation/Sources/Presentation/FeedCell/FeedCellView.swift
  HilingualPresentation/Sources/Presentation/FeedCell/FeedDiaryItem.swift
  HilingualPresentation/Sources/Presentation/FeedCell/FeedListViewController.swift
  HilingualPresentation/Sources/Presentation/FeedCell/FeedProfileListType.swift
  HilingualPresentation/Sources/Presentation/FeedCell/FeedProfileListViewController.swift
  HilingualPresentation/Sources/Presentation/FeedProfile/FeedProfileViewModel.swift
  HilingualPresentation/Sources/Presentation/FeedProfile/MyFeed/MyFeedProfileView.swift
  HilingualPresentation/Sources/Presentation/FeedProfile/MyFeed/MyFeedProfileViewController.swift
  HilingualPresentation/Sources/Presentation/FeedProfile/UserFeed/UserFeedProfileView.swift
  HilingualPresentation/Sources/Presentation/FeedProfile/UserFeed/UserFeedViewController.swift
Labels: 🔨 feat, 🦊 영서

#239 [feat] NotificatoinView ui 구현 + mocking
  Hilingual/App/AppDIContainer.swift
  HilingualData/Sources/HilingualData/Mapper/NotificationDTO+Mapper.swift
  HilingualData/Sources/HilingualData/Mapper/NotificationDetailDTO+Mapper.swift
  HilingualData/Sources/HilingualData/Repository/DefaultNotificationRepository.swift
  HilingualDomain/Sources/HilingualDomain/Entity/NotificationDetailEntity.swift
  HilingualDomain/Sources/HilingualDomain/Entity/NotificationEntity.swift
  HilingualDomain/Sources/HilingualDomain/Interface/Repository/NotificationRepository.swift
  HilingualDomain/Sources/HilingualDomain/UseCase/NotificationUseCase.swift
  HilingualNetwork/Sources/HilingualNetwork/DTO/NotificationDTO.swift
  HilingualNetwork/Sources/HilingualNetwork/DTO/NotificationDetailDTO.swift
  HilingualNetwork/Sources/HilingualNetwork/Service/DefaultNotificationService.swift
  HilingualNetwork/Sources/HilingualNetwork/Service/DefaultVerificationCodeService.swift
  HilingualPresentation/Sources/Presentation/Common/DeepLink/DeeplinkDestination.swift
  HilingualPresentation/Sources/Presentation/Common/DeepLink/DeeplinkManager.swift
  HilingualPresentation/Sources/Presentation/Common/DeepLink/DeeplinkParser.swift
  HilingualPresentation/Sources/Presentation/Common/Factory/ViewControllerFactory.swift
  HilingualPresentation/Sources/Presentation/NotificationHome/NotificationCell.swift
  HilingualPresentation/Sources/Presentation/NotificationHome/NotificationDetail/NotificationDetailModel.swift
  HilingualPresentation/Sources/Presentation/NotificationHome/NotificationDetail/NotificationDetailView.swift
  HilingualPresentation/Sources/Presentation/NotificationHome/NotificationDetail/NotificationDetailViewController.swift
  HilingualPresentation/Sources/Presentation/NotificationHome/NotificationDetail/NotificationDetailViewModel.swift
  HilingualPresentation/Sources/Presentation/NotificationHome/NotificationListViewController.swift
  HilingualPresentation/Sources/Presentation/NotificationHome/NotificationModel.swift
  HilingualPresentation/Sources/Presentation/NotificationHome/NotificationView.swift
  HilingualPresentation/Sources/Presentation/NotificationHome/NotificationViewController.swift
  HilingualPresentation/Sources/Presentation/NotificationHome/NotificationViewModel.swift
Labels: 🔨 feat, 🐥 현주

#247 [feat] Flow연결
  Hilingual/App/AppDIContainer.swift
  Hilingual/App/SceneDelegate.swift
  HilingualNetwork/Sources/HilingualNetwork/Service/DefaultAuthService.swift
  HilingualNetwork/Sources/HilingualNetwork/Service/DefaultOnBoardingService.swift
  HilingualPresentation/Sources/Presentation/Common/Components/Feed/FeedDiaryCell.swift
  HilingualPresentation/Sources/Presentation/Common/Components/Feed/FeedProfileView.swift
  HilingualPresentation/Sources/Presentation/Common/DeepLink/DeeplinkManager.swift
  HilingualPresentation/Sources/Presentation/Common/Extensions/BaseUIViewController+Navigation.swift
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Icon/24/ic_setting_24_ios.imageset/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Icon/24/ic_setting_24_ios.imageset/ic_setting_24_ios.svg
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Icon/24/ic_upload_24_ios.imageset/ic_upload_24_ios.png
  HilingualPresentation/Sources/Presentation/DiaryDetail/DiaryDetailViewController.swift
  HilingualPresentation/Sources/Presentation/Feed/FeedView.swift
  HilingualPresentation/Sources/Presentation/Feed/FeedViewController.swift
  HilingualPresentation/Sources/Presentation/Feed/FeedViewModel.swift
  HilingualPresentation/Sources/Presentation/FeedCell/FeedCellView.swift
  HilingualPresentation/Sources/Presentation/FeedCell/FeedDiaryItem.swift
  HilingualPresentation/Sources/Presentation/FeedCell/FeedListViewController.swift
  HilingualPresentation/Sources/Presentation/FeedProfile/FeedProfileViewModel.swift
  HilingualPresentation/Sources/Presentation/FeedProfile/MyFeed/MyFeedProfileView.swift
  HilingualPresentation/Sources/Presentation/FeedProfile/MyFeed/MyFeedProfileViewController.swift
  HilingualPresentation/Sources/Presentation/FeedProfile/UserFeed/UserFeedProfileView.swift
  HilingualPresentation/Sources/Presentation/FeedProfile/UserFeed/UserFeedViewController.swift
  HilingualPresentation/Sources/Presentation/FeedSearch/FeedSearchViewController.swift
  HilingualPresentation/Sources/Presentation/FollowList/TableView/FollowListCell.swift
  HilingualPresentation/Sources/Presentation/FollowList/ViewController/FollowerListViewController.swift
  HilingualPresentation/Sources/Presentation/FollowList/ViewController/FollowingListViewController.swift
  HilingualPresentation/Sources/Presentation/Home/HomeViewController.swift
  HilingualPresentation/Sources/Presentation/Login/LoginViewController.swift
  HilingualPresentation/Sources/Presentation/MyPage/BlockUser/BlockUserViewController.swift
  HilingualPresentation/Sources/Presentation/MyPage/BlockUser/BlockedUserCell.swift
  HilingualPresentation/Sources/Presentation/MyPage/MypageHome/MypageViewController.swift
  HilingualPresentation/Sources/Presentation/NotificationHome/NotificationSetting/NotificationSettingView.swift
  HilingualPresentation/Sources/Presentation/NotificationHome/NotificationSetting/NotificationSettingViewController.swift
  HilingualPresentation/Sources/Presentation/NotificationHome/NotificationSetting/NotificationSettingViewModel.swift
  HilingualPresentation/Sources/Presentation/NotificationHome/NotificationViewController.swift
  HilingualPresentation/Sources/Presentation/OnBoarding/OnBoardingView.swift
  HilingualPresentation/Sources/Presentation/SharedDiary/SharedDiaryViewController.swift
  HilingualPresentation/Sources/Presentation/Splash/SplashViewController.swift
  HilingualPresentation/Sources/Presentation/VerificationCode/VerificationCodeViewController.swift
Labels: 🔨 feat, 🐥 현주
