Repository Hi-lingual/Hilingual-iOS, pull requests merged in 2025-07, with the labels that each got.

#12 [add] 폰트 및 extension 추가
  Hilingual/Info.plist
  HilingualPresentation/Sources/Presentation/Common/Extensions/UIFont+.swift
  HilingualPresentation/Sources/Presentation/Common/Resources/Font/SUIT-Bold.ttf
  HilingualPresentation/Sources/Presentation/Common/Resources/Font/SUIT-ExtraBold.ttf
  HilingualPresentation/Sources/Presentation/Common/Resources/Font/SUIT-ExtraLight.ttf
  HilingualPresentation/Sources/Presentation/Common/Resources/Font/SUIT-Heavy.ttf
  HilingualPresentation/Sources/Presentation/Common/Resources/Font/SUIT-Light.ttf
  HilingualPresentation/Sources/Presentation/Common/Resources/Font/SUIT-Medium.ttf
  HilingualPresentation/Sources/Presentation/Common/Resources/Font/SUIT-Regular.ttf
  HilingualPresentation/Sources/Presentation/Common/Resources/Font/SUIT-SemiBold.ttf
  HilingualPresentation/Sources/Presentation/Common/Resources/Font/SUIT-Thin.ttf
Labels: ➕ add, 🐯 soeun

#13 [add] color system 구성 및 extension 추가
  HilingualPresentation/Sources/Presentation/Common/Extensions/UIColor+.swift
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/ColorSystem/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/ColorSystem/Grayscale/Black.colorset/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/ColorSystem/Grayscale/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/ColorSystem/Grayscale/Gray100.colorset/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/ColorSystem/Grayscale/Gray200.colorset/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/ColorSystem/Grayscale/Gray300.colorset/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/ColorSystem/Grayscale/Gray400.colorset/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/ColorSystem/Grayscale/Gray500.colorset/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/ColorSystem/Grayscale/Gray700.colorset/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/ColorSystem/Grayscale/Gray850.colorset/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/ColorSystem/Grayscale/dim.colorset/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/ColorSystem/Grayscale/white.colorset/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/ColorSystem/Main/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/ColorSystem/Main/HilingualBlack.colorset/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/ColorSystem/Main/HilingualBlue.colorset/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/ColorSystem/Main/HilingualOrange.colorset/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/ColorSystem/Symentic/AlertREd.colorset/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/ColorSystem/Symentic/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/ColorSystem/Symentic/InfoBlue.colorset/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/ColorSystem/WordChip/Adj_bg.colorset/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/ColorSystem/WordChip/Adj_text.colorset/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/ColorSystem/WordChip/Adverb_bg.colorset/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/ColorSystem/WordChip/Adverb_text.colorset/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/ColorSystem/WordChip/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/ColorSystem/WordChip/Interjection_bg.colorset/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/ColorSystem/WordChip/Noun_bg.colorset/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/ColorSystem/WordChip/Preposition_bg.colorset/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/ColorSystem/WordChip/Preposition_text.colorset/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/ColorSystem/WordChip/Pronoun_bg.colorset/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/ColorSystem/WordChip/Pronoun_text.colorset/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Image.imageset/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Image.imageset/스크린샷 2025-07-02 오후 9.37.17.png
Labels: ➕ add, 🐰 hyeyeon

#15 [chore] Color set의 white를 White로 변경
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/ColorSystem/Grayscale/White.colorset/Contents.json
Labels: ✏️ chore, 🐰 hyeyeon

#25 [fix] Font Targets 오류 해결
  HilingualPresentation/Package.swift
Labels: ⚒️ fix, 🐯 소은

#29 [feat] chip components 구현
  HilingualPresentation/Sources/Presentation/Common/Components/Chip.swift
Labels: 🔨 feat, 🐰 혜연

#28 [feat] textView Component 구현
  HilingualPresentation/Sources/Presentation/Common/Components/TextView.swift
Labels: 🔨 feat, 🐰 혜연

#34 [feat] HighlightTextView Component
  HilingualPresentation/Sources/Presentation/Common/Components/HighlightTextView.swift
Labels: 🔨 feat, 🐯 소은

#36 [feat] highlightingFeedback Component 구현
  HilingualPresentation/Sources/Presentation/Common/Components/Chip.swift
  HilingualPresentation/Sources/Presentation/Common/Components/HighlightingFeedback.swift
  HilingualPresentation/Sources/Presentation/Common/Extensions/UIStackView+.swift
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Chip/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Chip/aiChip.imageset/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Chip/aiChip.imageset/aiChip.png
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Chip/meChip.imageset/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Chip/meChip.imageset/meChip.png
Labels: 🔨 feat, 🐰 혜연

#37 [feat] 커스텀 텍스트필드 컴포넌트 구현
  HilingualPresentation/Sources/Presentation/Common/Base/BaseUiViewController.swift
  HilingualPresentation/Sources/Presentation/Common/Components/TextField.swift
  HilingualPresentation/Sources/Presentation/Common/Extensions/UIViewController+.swift
  HilingualPresentation/Sources/Presentation/Login/LoginView.swift
  HilingualPresentation/Sources/Presentation/Login/LoginViewController.swift
  HilingualPresentation/Sources/Presentation/Login/LoginViewModel.swift
Labels: 🔨 feat, 🐥 현주

#39 [feat] WordCard 컴포넌트 구현
  HilingualPresentation/Sources/Presentation/Common/Components/WordCard.swift
Labels: 🔨 feat, 🐯 소은

#38 [feat] 캘린더 컴포넌트 구현
  Hilingual.xcodeproj/project.pbxproj
  HilingualData/Package.swift
  HilingualDomain/Package.swift
  HilingualPresentation/Package.swift
  HilingualPresentation/Sources/Presentation/Common/Components/Calendar/CalendarHeaderView.swift
  HilingualPresentation/Sources/Presentation/Common/Components/Calendar/CalendarView.swift
  HilingualPresentation/Sources/Presentation/Common/Components/Calendar/CustomCalendarCell.swift
  HilingualPresentation/Sources/Presentation/Common/Components/Calendar/MonthPickerViewController.swift
Labels: 🔨 feat, 🦊 영서

#51 [chore] 수정된 이미지 에셋 추가
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Image/img_diary_empty_ios.imageset/img_diary_empty_ios.svg
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Image/img_diary_lock_ios.imageset/img_diary_lock_ios.svg
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Image/img_login_ios.imageset/img_login_ios.svg
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Image/img_logo_ios.imageset/img_logo_ios.svg
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Image/img_profile_normal_ios.imageset/img_profile_normal_ios.svg
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Image/img_search_ios.imageset/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Image/img_search_ios.imageset/img_search_ios.svg
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Image/img_word_ios.imageset/img_word_ios.svg
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/img_diary_empty_ios.imageset/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/img_diary_empty_ios.imageset/img_diary_empty_ios.svg
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/img_diary_lock_ios.imageset/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/img_diary_lock_ios.imageset/img_diary_lock_ios.svg
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/img_login_ios.imageset/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/img_login_ios.imageset/img_login_ios.svg
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/img_logo_ios.imageset/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/img_logo_ios.imageset/img_logo_ios.svg
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/img_profile_normal_ios.imageset/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/img_profile_normal_ios.imageset/img_profile_normal_ios.svg
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/img_word_ios.imageset/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/img_word_ios.imageset/img_word_ios.svg
Labels: ✏️ chore, 🦊 영서

#59 [feat] Modal 컴포넌트 구현
  HilingualPresentation/Sources/Presentation/Common/Components/Chip.swift
  HilingualPresentation/Sources/Presentation/Common/Components/HighlightingFeedback.swift
  HilingualPresentation/Sources/Presentation/Common/Components/Modal.swift
  HilingualPresentation/Sources/Presentation/Common/Components/TextView.swift
Labels: 🔨 feat, 🐰 혜연

#66 [feat] 프로필 뷰 컴포넌트 구현
  Hilingual.xcodeproj/project.pbxproj
  Hilingual.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  HilingualPresentation/Package.swift
  HilingualPresentation/Sources/Presentation/Common/Components/HomeView/ProfileView.swift
Labels: 🔨 feat, 🦊 영서

#69 [feat] 홈뷰 컴포넌트 구현
  HilingualPresentation/Sources/Presentation/Common/Components/HomeView/CardPreview.swift
  HilingualPresentation/Sources/Presentation/Common/Components/HomeView/CardTopicView.swift
  HilingualPresentation/Sources/Presentation/Common/Components/HomeView/DiaryLockView.swift
  HilingualPresentation/Sources/Presentation/Common/Components/HomeView/EmptyDiaryView.swift
Labels: 🔨 feat, 🦊 영서

#70 [feat] HomeVIew 구현
  HilingualPresentation/Sources/Presentation/Common/Components/Calendar/CalendarHeaderView.swift
  HilingualPresentation/Sources/Presentation/Common/Components/Calendar/CalendarView.swift
  HilingualPresentation/Sources/Presentation/Common/Components/HomeView/CardPreview.swift
  HilingualPresentation/Sources/Presentation/Common/Components/HomeView/ProfileView.swift
  HilingualPresentation/Sources/Presentation/Common/Components/SelectedInfo.swift
  HilingualPresentation/Sources/Presentation/Example/ExampleView.swift
  HilingualPresentation/Sources/Presentation/Example/ExampleViewController.swift
  HilingualPresentation/Sources/Presentation/Example/ExampleViewModel.swift
  HilingualPresentation/Sources/Presentation/Home/HomeView.swift
  HilingualPresentation/Sources/Presentation/Home/HomeViewController.swift
Labels: 🔨 feat, 🦊 영서

#67 [feat] Dialog 컴포넌트 구현
  HilingualPresentation/Sources/Presentation/Common/Components/Dialog.swift
  HilingualPresentation/Sources/Presentation/DiaryWriting/DiaryWritingViewController.swift
Labels: 🔨 feat, 🐰 혜연

#77 [chore] 홈뷰 레이아웃 수정
  HilingualPresentation/Sources/Presentation/Common/Components/HomeView/CardPreview.swift
  HilingualPresentation/Sources/Presentation/Common/Components/HomeView/CardTopicView.swift
  HilingualPresentation/Sources/Presentation/Common/Components/HomeView/DiaryLockView.swift
  HilingualPresentation/Sources/Presentation/Common/Components/HomeView/EmptyDiaryView.swift
  HilingualPresentation/Sources/Presentation/Common/Components/HomeView/SelectedInfo.swift
  HilingualPresentation/Sources/Presentation/Home/HomeView.swift
  HilingualPresentation/Sources/Presentation/Home/HomeViewController.swift
  HilingualPresentation/Sources/Presentation/Home/HomeViewModel.swift
Labels: ✏️ chore, 🦊 영서

#75 [feat] DiaryDetailView 구현 (일기 확인)
  Hilingual/App/AppDIContainer.swift
  HilingualData/Sources/HilingualData/Repository/DefaultBookmarkRepository.swift
  HilingualData/Sources/HilingualData/Repository/DefaultDiaryDetailRepository.swift
  HilingualDomain/Sources/HilingualDomain/Entity/DiaryDetailEntity.swift
  HilingualDomain/Sources/HilingualDomain/Entity/DiaryFeedbackEntity.swift
  HilingualDomain/Sources/HilingualDomain/Entity/PhraseEntity.swift
  HilingualDomain/Sources/HilingualDomain/Interface/Repository/BookmarkRepository.swift
  HilingualDomain/Sources/HilingualDomain/Interface/Repository/DiaryDetailRepository.swift
  HilingualDomain/Sources/HilingualDomain/UseCase/DiaryDetailUseCase.swift
  HilingualNetwork/Sources/HilingualNetwork/DTO/BookmarkDTO.swift
  HilingualNetwork/Sources/HilingualNetwork/DTO/DiaryDetailDTO.swift
  HilingualNetwork/Sources/HilingualNetwork/Service/BookmarkService.swift
  HilingualNetwork/Sources/HilingualNetwork/Service/DiaryDetailService.swift
  HilingualPresentation/Sources/Presentation/Common/Components/HighlightTextView.swift
  HilingualPresentation/Sources/Presentation/Common/Components/HighlightingFeedback.swift
  HilingualPresentation/Sources/Presentation/Common/Factory/ViewControllerFactory.swift
  HilingualPresentation/Sources/Presentation/Diarydetail/DetailImageView.swift
  HilingualPresentation/Sources/Presentation/Diarydetail/DiaryDetailView.swift
  HilingualPresentation/Sources/Presentation/Diarydetail/DiaryDetailViewController.swift
  HilingualPresentation/Sources/Presentation/Diarydetail/DiaryDetailViewModel.swift
  HilingualPresentation/Sources/Presentation/Diarydetail/FeedbackView.swift
  HilingualPresentation/Sources/Presentation/Diarydetail/FeedbackViewController.swift
  HilingualPresentation/Sources/Presentation/Diarydetail/FeedbackViewModel.swift
  HilingualPresentation/Sources/Presentation/Diarydetail/VocaView.swift
  HilingualPresentation/Sources/Presentation/Diarydetail/VocaViewController.swift
  HilingualPresentation/Sources/Presentation/Diarydetail/VocaViewModel.swift
Labels: 🔨 feat, 🐯 소은

#86 [fix] PhraseData 관련 수정사항
  HilingualDomain/Sources/HilingualDomain/Entity/PhraseEntity.swift
  HilingualPresentation/Sources/Presentation/Common/Components/WordCard.swift
  HilingualPresentation/Sources/Presentation/Diarydetail/Dummy/PhraseData.swift
  HilingualPresentation/Sources/Presentation/Diarydetail/VocaView.swift
  HilingualPresentation/Sources/Presentation/Diarydetail/VocaViewController.swift
Labels: ⚒️ fix, 🐯 소은

#90 [network] 애플로그인 + 자동 로그인 + 토큰 재발급 구현
  Hilingual/App/AppDIContainer.swift
  Hilingual/App/SceneDelegate.swift
  HilingualData/Sources/HilingualData/Mapper/LoginResponseDTO+Mapper.swift
  HilingualData/Sources/HilingualData/Mapper/TokenRefreshResponseDTO+Mapper.swift
  HilingualData/Sources/HilingualData/Repository/DefaultAuthRepository.swift
  HilingualData/Sources/HilingualData/Repository/DefaultOnBoardingRepository.swift
  HilingualData/Sources/HilingualData/Token/DefaultTokenStore.swift
  HilingualDomain/Sources/HilingualDomain/Entity/LoginResponseEntity.swift
  HilingualDomain/Sources/HilingualDomain/Entity/ProfileEntity.swift
  HilingualDomain/Sources/HilingualDomain/Interface/Repository/AuthRepository.swift
  HilingualDomain/Sources/HilingualDomain/Interface/Repository/OnBoardingRepository.swift
  HilingualDomain/Sources/HilingualDomain/UseCase/OnBoardingUseCase.swift
  HilingualDomain/Sources/HilingualDomain/UseCase/SocialLoginUseCase.swift
  HilingualDomain/Sources/HilingualDomain/UseCase/TokenStoreUseCase.swift
  HilingualNetwork/Sources/HilingualNetwork/API/AuthAPI.swift
  HilingualNetwork/Sources/HilingualNetwork/API/OnBoardingAPI.swift
  HilingualNetwork/Sources/HilingualNetwork/DTO/EmptyData.swift
  HilingualNetwork/Sources/HilingualNetwork/DTO/LoginResponseDTO.swift
  HilingualNetwork/Sources/HilingualNetwork/DTO/OnBoardingReponseDTO.swift
  HilingualNetwork/Sources/HilingualNetwork/DTO/TokenRefreshResponseDTO.swift
  HilingualNetwork/Sources/HilingualNetwork/Foundation/BaseAPIResponse.swift
  HilingualNetwork/Sources/HilingualNetwork/Foundation/TargetType/BaseTargetType.swift
  HilingualNetwork/Sources/HilingualNetwork/Service/DefaultAuthService.swift
  HilingualNetwork/Sources/HilingualNetwork/Service/DefaultOnBoardingService.swift
  HilingualNetwork/Sources/HilingualNetwork/Service/DefaultTokenRefreshService.swift
  HilingualNetwork/Sources/HilingualNetwork/Token/UserDefault.swift
  HilingualNetwork/Sources/HilingualNetwork/Token/UserDefaultHandler.swift
  HilingualPresentation/Sources/Presentation/Common/Utils/NavigationUtil.swift
  HilingualPresentation/Sources/Presentation/Login/LoginViewController.swift
  HilingualPresentation/Sources/Presentation/Login/LoginViewModel.swift
  HilingualPresentation/Sources/Presentation/OnBoarding/OnBoardingViewController.swift
  HilingualPresentation/Sources/Presentation/OnBoarding/OnBoardingViewModel.swift
  HilingualPresentation/Sources/Presentation/Splash/SplashView.swift
  HilingualPresentation/Sources/Presentation/Splash/SplashViewController.swift
  HilingualPresentation/Sources/Presentation/Splash/SplashViewModel.swift
Labels: 🔨 feat, 🐥 현주

#88 [feat] LoadingView 구현(로띠)
  Hilingual.xcodeproj/project.pbxproj
  Hilingual.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Hilingual/App/AppDIContainer.swift
  HilingualPresentation/Package.swift
  HilingualPresentation/Sources/Presentation/Common/Factory/ViewControllerFactory.swift
  HilingualPresentation/Sources/Presentation/Common/Resources/Lottie/feedback1.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Lottie/feedback2.json
  HilingualPresentation/Sources/Presentation/DiaryWriting/DiaryWritingView.swift
  HilingualPresentation/Sources/Presentation/DiaryWriting/DiaryWritingViewController.swift
  HilingualPresentation/Sources/Presentation/Loading/LoadingView.swift
  HilingualPresentation/Sources/Presentation/Loading/LoadingViewController.swift
  HilingualPresentation/Sources/Presentation/Loading/LoadingViewModel.swift
Labels: 🔨 feat, 🐰 혜연

#95 [hotfix] 괄호 누락 수정 및 스플래쉬 뷰 수정
  HilingualPresentation/Sources/Presentation/DiaryWriting/DiaryWritingViewController.swift
  HilingualPresentation/Sources/Presentation/Splash/SplashViewController.swift
Labels: 🚨 hotfix, 🐰 혜연

#91 [feat] OCR 구현
  Hilingual.xcodeproj/project.pbxproj
  Hilingual/Info.plist
  HilingualPresentation/Sources/Presentation/Common/Components/TextView.swift
  HilingualPresentation/Sources/Presentation/Common/Factory/ViewControllerFactory.swift
  HilingualPresentation/Sources/Presentation/DiaryWriting/DiaryWritingView.swift
  HilingualPresentation/Sources/Presentation/DiaryWriting/DiaryWritingViewController.swift
  HilingualPresentation/Sources/Presentation/DiaryWriting/VisionKitManager.swift
  HilingualPresentation/Sources/Presentation/Home/HomeViewController.swift
Labels: 🔨 feat, 🐰 혜연

#98 [network] profileview API 연결
  HilingualData/Sources/HilingualData/Repository/DefaultHomeRepository.swift
  HilingualDomain/Sources/HilingualDomain/Entity/UserInfoEntity.swift
  HilingualDomain/Sources/HilingualDomain/Interface/Repository/HomeRepository.swift
  HilingualDomain/Sources/HilingualDomain/UseCase/HomeUseCase.swift
  HilingualNetwork/Sources/HilingualNetwork/API/HomeAPI.swift
  HilingualNetwork/Sources/HilingualNetwork/DTO/UserInfoDTO.swift
  HilingualNetwork/Sources/HilingualNetwork/Service/DefaultHomeService.swift
  HilingualPresentation/Sources/Presentation/Example/ExampleViewController.swift
  HilingualPresentation/Sources/Presentation/Example/ExampleViewModel.swift
  HilingualPresentation/Sources/Presentation/Home/HomeViewController.swift
  HilingualPresentation/Sources/Presentation/Home/HomeViewModel.swift
Labels: 🛜 network, 🦊 영서

#101 [chore] 달력 셀 텍스트라벨 색 변경
  HilingualPresentation/Sources/Presentation/Common/Components/Calendar/CustomCalendarCell.swift
Labels: ✏️ chore, 🦊 영서

#102 [chore] CTA버튼 터치영역 오류 수정
  HilingualPresentation/Sources/Presentation/Common/Components/CTAButton.swift
Labels: ✏️ chore, 🦊 영서

#105 [network] 홈 API 구현
  HilingualData/Sources/HilingualData/Mapper/DiaryInfoDTO+Mapper.swift
  HilingualData/Sources/HilingualData/Mapper/MonthInfoDTO+Mapper.swift
  HilingualData/Sources/HilingualData/Mapper/TopicDTO+Mapper.swift
  HilingualData/Sources/HilingualData/Repository/DefaultHomeRepository.swift
  HilingualDomain/Sources/HilingualDomain/Entity/DiaryInfoEntity.swift
  HilingualDomain/Sources/HilingualDomain/Entity/HomeEntity.swift
  HilingualDomain/Sources/HilingualDomain/Entity/MonthInfoEntity.swift
  HilingualDomain/Sources/HilingualDomain/Entity/TopicEntity.swift
  HilingualDomain/Sources/HilingualDomain/Interface/Repository/HomeRepository.swift
  HilingualDomain/Sources/HilingualDomain/UseCase/HomeUseCase.swift
  HilingualNetwork/Sources/HilingualNetwork/API/HomeAPI.swift
  HilingualNetwork/Sources/HilingualNetwork/DTO/DiaryInfoDTO.swift
  HilingualNetwork/Sources/HilingualNetwork/DTO/MonthInfoDTO.swift
  HilingualNetwork/Sources/HilingualNetwork/DTO/TopicDTO.swift
  HilingualNetwork/Sources/HilingualNetwork/Foundation/OrderedURLEncoding.swift
  HilingualNetwork/Sources/HilingualNetwork/Service/DefaultHomeService.swift
  HilingualPresentation/Sources/Presentation/Common/Components/Calendar/CalendarHeaderView.swift
  HilingualPresentation/Sources/Presentation/Common/Components/Calendar/CalendarView.swift
  HilingualPresentation/Sources/Presentation/Common/Components/HomeView/SelectedInfo.swift
  HilingualPresentation/Sources/Presentation/Common/Extensions/Date+.swift
  HilingualPresentation/Sources/Presentation/Home/HomeView.swift
  HilingualPresentation/Sources/Presentation/Home/HomeViewController.swift
  HilingualPresentation/Sources/Presentation/Home/HomeViewModel.swift
Labels: 🛜 network, 🦊 영서

#108 [chore] HighlightTextView 하이라이팅 폰트 수정
  HilingualPresentation/Sources/Presentation/Common/Components/HighlightTextView.swift
Labels: ✏️ chore, 🐯 소은

#122 [chore] diaryDetialView 연결
  Hilingual/App/AppDIContainer.swift
  HilingualPresentation/Sources/Presentation/Common/Components/HomeView/SelectedInfo.swift
  HilingualPresentation/Sources/Presentation/Common/Factory/ViewControllerFactory.swift
  HilingualPresentation/Sources/Presentation/Diarydetail/DiaryDetailViewController.swift
  HilingualPresentation/Sources/Presentation/Diarydetail/DiaryDetailViewModel.swift
  HilingualPresentation/Sources/Presentation/Home/HomeViewController.swift
  HilingualPresentation/Sources/Presentation/Loading/LoadingViewController.swift
  HilingualPresentation/Sources/Presentation/Loading/LoadingViewModel.swift
  HilingualPresentation/Sources/Presentation/WordBook/WordBookViewController.swift
Labels: 🔨 feat, 🐯 소은

#129 [feat] 데이트피커 모달 구현
  HilingualPresentation/Sources/Presentation/Common/Components/Calendar/CalendarHeaderView.swift
  HilingualPresentation/Sources/Presentation/Common/Components/Calendar/MonthPickerModal.swift
  HilingualPresentation/Sources/Presentation/Common/Components/Calendar/MonthPickerViewController.swift
  HilingualPresentation/Sources/Presentation/Home/HomeViewController.swift
Labels: ✏️ chore, 🦊 영서

#128 [feat] appicon 추가 + 모달 에니메이션 추가
  Hilingual.xcodeproj/project.pbxproj
  Hilingual/App/Config/AppIcon.xcassets/AppIcon.appiconset/100.png
  Hilingual/App/Config/AppIcon.xcassets/AppIcon.appiconset/102.png
  Hilingual/App/Config/AppIcon.xcassets/AppIcon.appiconset/1024.png
  Hilingual/App/Config/AppIcon.xcassets/AppIcon.appiconset/108.png
  Hilingual/App/Config/AppIcon.xcassets/AppIcon.appiconset/114.png
  Hilingual/App/Config/AppIcon.xcassets/AppIcon.appiconset/120.png
  Hilingual/App/Config/AppIcon.xcassets/AppIcon.appiconset/128.png
  Hilingual/App/Config/AppIcon.xcassets/AppIcon.appiconset/144.png
  Hilingual/App/Config/AppIcon.xcassets/AppIcon.appiconset/152.png
  Hilingual/App/Config/AppIcon.xcassets/AppIcon.appiconset/16.png
  Hilingual/App/Config/AppIcon.xcassets/AppIcon.appiconset/167.png
  Hilingual/App/Config/AppIcon.xcassets/AppIcon.appiconset/172.png
  Hilingual/App/Config/AppIcon.xcassets/AppIcon.appiconset/180.png
  Hilingual/App/Config/AppIcon.xcassets/AppIcon.appiconset/196.png
  Hilingual/App/Config/AppIcon.xcassets/AppIcon.appiconset/20.png
  Hilingual/App/Config/AppIcon.xcassets/AppIcon.appiconset/216.png
  Hilingual/App/Config/AppIcon.xcassets/AppIcon.appiconset/234.png
  Hilingual/App/Config/AppIcon.xcassets/AppIcon.appiconset/256.png
  Hilingual/App/Config/AppIcon.xcassets/AppIcon.appiconset/258.png
  Hilingual/App/Config/AppIcon.xcassets/AppIcon.appiconset/29.png
  Hilingual/App/Config/AppIcon.xcassets/AppIcon.appiconset/32.png
  Hilingual/App/Config/AppIcon.xcassets/AppIcon.appiconset/40.png
  Hilingual/App/Config/AppIcon.xcassets/AppIcon.appiconset/48.png
  Hilingual/App/Config/AppIcon.xcassets/AppIcon.appiconset/50.png
  Hilingual/App/Config/AppIcon.xcassets/AppIcon.appiconset/512.png
  Hilingual/App/Config/AppIcon.xcassets/AppIcon.appiconset/55.png
  Hilingual/App/Config/AppIcon.xcassets/AppIcon.appiconset/57.png
  Hilingual/App/Config/AppIcon.xcassets/AppIcon.appiconset/58.png
  Hilingual/App/Config/AppIcon.xcassets/AppIcon.appiconset/60.png
  Hilingual/App/Config/AppIcon.xcassets/AppIcon.appiconset/64.png
  Hilingual/App/Config/AppIcon.xcassets/AppIcon.appiconset/66.png
  Hilingual/App/Config/AppIcon.xcassets/AppIcon.appiconset/72.png
  Hilingual/App/Config/AppIcon.xcassets/AppIcon.appiconset/76.png
  Hilingual/App/Config/AppIcon.xcassets/AppIcon.appiconset/80.png
  Hilingual/App/Config/AppIcon.xcassets/AppIcon.appiconset/87.png
  Hilingual/App/Config/AppIcon.xcassets/AppIcon.appiconset/88.png
  Hilingual/App/Config/AppIcon.xcassets/AppIcon.appiconset/92.png
  Hilingual/App/Config/AppIcon.xcassets/AppIcon.appiconset/Contents.json
  Hilingual/App/Config/AppIcon.xcassets/Contents.json
  HilingualNetwork/Sources/HilingualNetwork/DTO/EmptyData.swift
  HilingualNetwork/Sources/HilingualNetwork/Service/DefaultOnBoardingService.swift
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  HilingualPresentation/Sources/Presentation/WordBook/Modal/SortOptionModal.swift
  HilingualPresentation/Sources/Presentation/WordBook/WordBookViewController.swift
Labels: 🔨 feat, 🐥 현주

#130 [feat] AI 신고하기 피드백 웹 뷰 연결
  HilingualPresentation/Sources/Presentation/Diarydetail/DiaryDetailViewController.swift
  HilingualPresentation/Sources/Presentation/Diarydetail/FeedbackView.swift
Labels: 🔨 feat, 🐯 소은

#138 [refactor] popToRootViewController로 변경
  HilingualPresentation/Sources/Presentation/Loading/LoadingViewController.swift
Labels: ⭐️ refactor, 🐰 혜연

#139 [refactor] 홈뷰 QA 수정
  HilingualPresentation/Sources/Presentation/Common/Components/CTAButton.swift
  HilingualPresentation/Sources/Presentation/Common/Components/Calendar/CalendarHeaderView.swift
  HilingualPresentation/Sources/Presentation/Common/Components/Calendar/CalendarView.swift
  HilingualPresentation/Sources/Presentation/Common/Components/HomeView/ProfileView.swift
  HilingualPresentation/Sources/Presentation/Common/Components/HomeView/SelectedInfo.swift
  HilingualPresentation/Sources/Presentation/Home/HomeView.swift
  HilingualPresentation/Sources/Presentation/Home/HomeViewController.swift
Labels: ⭐️ refactor, 🦊 영서

#146 [chore] 엠티뷰 높이 차 문제 해결
  HilingualPresentation/Sources/Presentation/Common/Components/HomeView/DiaryLockView.swift
  HilingualPresentation/Sources/Presentation/Common/Components/HomeView/EmptyDiaryView.swift
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Image/img_diary_empty_ios.imageset/img_diary_empty_ios.svg
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Image/img_diary_lock_ios.imageset/img_diary_lock_ios.svg
Labels: ✏️ chore, 🦊 영서

#151 [chore] 데모데이 주제 제한 풀기
  HilingualPresentation/Sources/Presentation/Common/Components/HomeView/SelectedInfo.swift
Labels: ✏️ chore, 🦊 영서

#155 [chore] viewWillAppear 수정
  HilingualPresentation/Sources/Presentation/Home/HomeViewController.swift
  HilingualPresentation/Sources/Presentation/Home/HomeViewModel.swift
Labels: 🚨 hotfix, 🦊 영서

#156 [chore] Underline 길이 수정
  HilingualPresentation/Sources/Presentation/Common/Components/UnderlineSegmentedControl.swift
  HilingualPresentation/Sources/Presentation/Common/Components/WordCard.swift
  HilingualPresentation/Sources/Presentation/Diarydetail/FeedbackView.swift
Labels: ✏️ chore, 🐯 소은

#164 [add] README.md 작성
  README.md
Labels: ➕ add, 🦊 영서

#162 [feat] 탭바 커뮤니티, 마이페이지 준비 중 페이지 추가
  HilingualPresentation/Sources/Presentation/Common/Base/TabBarViewController.swift
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Image/img_preparing_ios.imageset/Contents.json
  HilingualPresentation/Sources/Presentation/Common/Resources/Assets.xcassets/Image/img_preparing_ios.imageset/img_preparing_ios.svg
  HilingualPresentation/Sources/Presentation/Preparing/PreparingViewController.swift
Labels: 🔨 feat, 🐥 현주
